USE [master]
GO
/****** Object:  Database [WebApi]    Script Date: 12.02.2023 16:51:19 ******/
CREATE DATABASE [WebApi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebApi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WebApi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebApi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WebApi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [WebApi] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebApi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [WebApi] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [WebApi] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [WebApi] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [WebApi] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [WebApi] SET ARITHABORT OFF 
GO
ALTER DATABASE [WebApi] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [WebApi] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [WebApi] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [WebApi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [WebApi] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [WebApi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [WebApi] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [WebApi] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [WebApi] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [WebApi] SET  DISABLE_BROKER 
GO
ALTER DATABASE [WebApi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [WebApi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [WebApi] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [WebApi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [WebApi] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [WebApi] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [WebApi] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [WebApi] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [WebApi] SET  MULTI_USER 
GO
ALTER DATABASE [WebApi] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [WebApi] SET DB_CHAINING OFF 
GO
ALTER DATABASE [WebApi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [WebApi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [WebApi] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [WebApi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [WebApi] SET QUERY_STORE = OFF
GO
USE [WebApi]
GO
/****** Object:  Table [dbo].[Results]    Script Date: 12.02.2023 16:51:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Results](
	[allTime] [bigint] NULL,
	[minDate] [datetime] NULL,
	[averageSeconds] [float] NULL,
	[averageN] [float] NULL,
	[medianN] [float] NULL,
	[maxN] [float] NULL,
	[minN] [float] NULL,
	[count] [int] NULL,
	[fileName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Results] PRIMARY KEY CLUSTERED 
(
	[fileName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Values]    Script Date: 12.02.2023 16:51:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Values](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[fileName] [varchar](50) NOT NULL,
	[date] [datetime] NOT NULL,
	[seconds] [int] NOT NULL,
	[n] [float] NOT NULL,
 CONSTRAINT [PK_Values] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Values]  WITH CHECK ADD  CONSTRAINT [FK_Values_Results] FOREIGN KEY([fileName])
REFERENCES [dbo].[Results] ([fileName])
GO
ALTER TABLE [dbo].[Values] CHECK CONSTRAINT [FK_Values_Results]
GO
USE [master]
GO
ALTER DATABASE [WebApi] SET  READ_WRITE 
GO
